- name: Build Armbian image
  uses: armbian/build@main
  with:
    armbian_token: ${{ secrets.GITHUB_TOKEN }}

    armbian_board: rk322x-box
    armbian_release: bookworm
    armbian_kernel_branch: current
    armbian_ui: minimal

    armbian_compress: true
    armbian_artifacts: true
